#If Server Or ThickClientOrdinaryApplication Or ExternalConnection Then

#Region EventHandlers

Procedure BeforeWrite(Cancel)
	
	If DataExchange.Load Then
		Return;
	EndIf;
	
	If ValueIsFilled(Owner) Then
		AdditionalValueOwner = CommonUse.ObjectAttributeValue(Owner,
			"AdditionalValueOwner");
		
		If ValueIsFilled(AdditionalValueOwner) Then
			ErrorDescription = StringFunctionsClientServer.SubstituteParametersInString(
				NStr("en = 'Additional values for the %1 property generated by sample
		           |of the %2 property should be created for the sample property.'"),
				Owner,
				AdditionalValueOwner);
			
			If IsNew() Then
				Raise ErrorDescription;
			Else
				Message = New UserMessage;
				Message.Text = ErrorDescription;
				Message.Message();
			EndIf;
		EndIf;
	EndIf;
	
EndProcedure

#EndRegion

#EndIf
